name: Mike Fowler
author: Mike Fowler
url: 'http://mikefowler.me'
email: mike@mikefowler.me

css: '/assets/css'
js: '/assets/scripts'
images: '/assets/images'

post:
  template: _templates/_post.txt
  extension: md

page:
  template: _templates/_page.txt
  extension: md

git:
  branch: master

editor: subl

disqus:
  prod: 
    shortname: mikefowler
  dev:
    shortname: mikefowler-dev

markdown: redcarpet

excerpt_separator: <!-- more -->

pygments: true
permalink: /:year/:month/:day/:title/

exclude: [
  'node_modules',
  'assets/sass',
  'Gruntfile.js',
  'mikefowler.me.sublime-project',
  'mikefowler.me.sublime-workspace',
  'package.json',
  'README.md',
  'vendor',
  'config.rb',
  'Gemfile',
  'Gemfile.lock',
  'CNAME'
]